### ISSUE TITLE
Dependabot non updated dependencies

### ISSUE THREAD

**Issue by jbelien** [geo6/geocoder#15]
@dependabot-bot  doesn't seem to update following PHP dependencies :

- [`guzzlehttp/guzzle`](https://packagist.org/packages/guzzlehttp/guzzle) : 6.3.0 to 6.3.2
- [`zendframework/zend-stdlib`](https://packagist.org/packages/zendframework/zend-stdlib) : 3.1.0 to 3.1.1
- [`zendframework/zend-stratigility`](https://packagist.org/packages/zendframework/zend-stratigility) : 3.0.0 to 3.0.1

Ping @greysteil @dependabot ! Thanks :)

**Comment by jbelien** [comment]
Even though it would be awesome that @dependabot-bot update also "sub-dependencies" but maybe it's out the scope of @dependabot-bot.

**Comment by greysteil** [comment]
We'll automatically update sub-dependencies if there a vulnerabilities in them, and have a "secret" option to update them as normal - I can enable it for you if you'd like?

**Comment by jbelien** [comment]
Oh nice ! Every discovery makes @dependabot-bot even better :P

If you enable it will it be enabled for all my repositories or just for this one ?

**Comment by greysteil** [comment]
Only this one (or any repos you ask me for)

**Comment by jbelien** [comment]
I'll take care of it myself then, so it's consistent for all my repositories (I don't want to bother you for every new repository :D).

Any reason to keep that option "secret" and not allowing users to enable this themselves ?

**Comment by greysteil** [comment]
Just that it's in beta and I wasn't sure if there'd be enough demand to keep it around. There's one person using it at the moment, but I'll remember you want it, too, when I make the call on whether to add it to the UI 🙂.

**Comment by jbelien** [comment]
Awesome 👍 
Thanks for all the good work ! 💪
